// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/6496aaf406610c3276e313a1
###
GET http://localhost:8080/contacts/6496aaf406610c3276e313a2
###
GET http://localhost:8080/contacts/6496aaf406610c3276e313a3

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/6496aaf406610c3276e313a1
###
GET https://cse341-instructor.herokuapp.com/contacts/6496aaf406610c3276e313a2
###
GET https://cse341-instructor.herokuapp.com/contacts/6496aaf406610c3276e313a3